version: "3"
services:
  nginxproxy:
    image: itzzjb/nginxproxy
    build: ./nginx
    ports:
      - 80:80
  nodejsserver:
    image: itzzjb/nodejsserver
    build: ./server
    ports:
      - 3000:3000
