version: "3"
services:
  nginxproxy:
    image: itzzjb/nginxproxy
    build: ./nginx
    ports:
      - 80:80
  nodejsserver:
    image: itzzjb/nodejsserver
    build: ./server
    ports:
      - 3000:3000
# But because I have a M1 Mac, and the images built on my M1 Mac will not work on an AWS instance,
# I will have to build the images on the AWS instance.
# So, I would need to upload all the files to the AWS instance.
