version: "3"
services:
  nginxproxy:
    image: itzzjb/nginxproxy
    build: ./nginx
    ports:
      - 80:80
    networks:
      - nginxtonode
  nodejsserver:
    image: itzzjb/nodejsserver
    build: ./server
    ports:
      - 3000:3000
    networks:
      - nginxtonode
networks:
  nginxtonode:
    driver: bridge
